### ISSUE TITLE
Does not work if a checkout step is removed 

### ISSUE THREAD

**Issue by jakemumu** [solidusio-contrib/solidus_tracking#29]
Spent some time trying to figure out why this gem wasn't working for it. It turns out that if you remove some checkout steps the events stop firing.

```
      remove_checkout_step :address
      remove_checkout_step :delivery
```

^^ adding this will cause the events to be skipped. 

Is there any suggestion on a different way I could pass over these checkout steps and keep the events occurring?

**Comment by aldesantis** [comment]
@jakemumu as a workaround, you could fire the events yourself (via solidus_tracking) for now. solidus_tracking tries to be as smart as possible to fire the standard events automatically, but with custom setups it can be hard to hook into the right point.

A more permanent solution would be to allow the gem to accept the order state as an external parameter rather than reading it from `@order.state`, so that it can still fire the right events even if you change the checkout steps.

I need to give this some more thought — the long term plan is for solidus_tracking to be embedded in solidus_core, so that there's no need for an additional layer of complexity and you can just implement your trackers directly on top of stock Solidus.

**Comment by jakemumu** [comment]
Yeah it might be nice if in the config you could override the step at which the events were sent, for me, I forward all orders straight to payment and then have a single page checkout. 

The strange thing was that I edited the actions where the callbacks are created, but they still weren't calling when I changed: 

```
          base.state_machine.after_transition to: :address, do: :track_started_checkout
```

to:

```
          base.state_machine.after_transition to: :payment, do: :track_started_checkout
```

It still wasn't firing -- what did for now, is not remove any checkout steps and just override the checkout controller to call next on the order if the state is address or delivery before rendering. It's working fine but resulted in a lot more overrides needed to keep it working. 

If I can get it to work with:

```
base.state_machine.after_transition to: :payment, do: :track_started_checkout
```

I'll try and set it up to use a config setting and post a PR if that's good solution? I'm a very novice rails developer so when things don't work -- especially things like a state machine -- it's very difficult for me to figure out.
